name: Terraform Digger Workflow

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed, opened, synchronize, reopened ]
  issue_comment:
    types: [created]
    if: contains(github.event.comment.body, 'digger')
  workflow_dispatch:

permissions:
  contents: write      # required to merge PRs
  actions: write       # required for plan persistence
  id-token: write      # required for workload-identity-federation
  pull-requests: write # required to post PR comments
  statuses: write      # required to validate combined PR status

jobs:
  digger-job:
    uses: drcash-brazil/drcash_github_actions/.github/workflows/terraform-cicd-digger.yaml@v0.0.2-terraform-cicd
    secrets: 
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY}}
      GH_PERSONAL_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN}}
